export enum CallMode {
  EDIT_INSTANCE = 'EDIT_INSTANCE',
  NEW_INSTANCE = 'NEW_INSTANCE',
  INSPECTION = 'INSPECTION',
  SURRENDER = 'SURRENDER',
  TIMEOUT = 'TIMEOUT',
  EXPLODE = 'EXPLODE',
  TESTER = 'TESTER',
  LOSE = 'LOSE',
  WIN = 'WIN',
  DUPLICATE = 'DUPLICATE'
}
